name: Sync Copilot Instructions

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install yq
        run: |
          sudo apt-get update
          sudo apt-get install -y yq

      - name: Load hierarchy or skip
        run: |
          echo "=== DEBUG: Checking for hierarchy file at .copilot/copilot-hierarchy.yml ==="
          if [ -f .copilot/copilot-hierarchy.yml ]; then
            echo "✅ FOUND: application-level hierarchy file at path [.copilot/copilot-hierarchy.yml]"
          else
            echo "❌ copilot-hierarchy.yml missing at the application level (.copilot/copilot-hierarchy.yml)"
            echo "✅ skipping Copilot sync for application-level config"
            exit 0
          fi

          ORG=$(yq '.org' .copilot/copilot-hierarchy.yml)
          DIV=$(yq '.division' .copilot/copilot-hierarchy.yml)
          SUBDIV=$(yq '.subdivision' .copilot/copilot-hierarchy.yml)
          APP=$(yq '.application' .copilot/copilot-hierarchy.yml)

          if [ -z "$ORG" ]; then
            echo "❌ ORG not specified in copilot-hierarchy.yml"
            echo "✅ skipping Copilot sync for org level"
            exit 0
          else
            echo "✅ ORG found: $ORG"
          fi

          if [ -z "$DIV" ]; then
            echo "❌ DIVISION not specified in copilot-hierarchy.yml"
            echo "✅ skipping Copilot sync for division level"
            exit 0
          else
            echo "✅ DIVISION found: $DIV"
          fi

          if [ -z "$SUBDIV" ]; then
            echo "❌ SUBDIVISION not specified in copilot-hierarchy.yml"
            echo "✅ skipping Copilot sync for subdivision level"
            exit 0
          else
            echo "✅ SUBDIVISION found: $SUBDIV"
          fi

          if [ -z "$APP" ]; then
            echo "❌ APPLICATION not specified in copilot-hierarchy.yml"
            echo "✅ skipping Copilot sync for application level"
            exit 0
          else
            echo "✅ APPLICATION found: $APP"
          fi

          echo "=== DEBUG: hierarchy values successfully loaded from application level ==="
          echo "ORG=$ORG"
          echo "DIV=$DIV"
          echo "SUBDIV=$SUBDIV"
          echo "APP=$APP"

          echo "ORG=$ORG" >> $GITHUB_ENV
          echo "DIV=$DIV" >> $GITHUB_ENV
          echo "SUBDIV=$SUBDIV" >> $GITHUB_ENV
          echo "APP=$APP" >> $GITHUB_ENV


      - name: Checkout subdivision instructions
        if: env.ORG != ''
        continue-on-error: true
        uses: actions/checkout@v4
        with:
          repository: ${{ env.ORG }}/${{ env.SUBDIV }}-copilot-instructions
          path: subdivision-instructions

      - name: Merge Copilot Instructions
        if: env.ORG != ''
        run: |
          mkdir -p .copilot
          cp -Rn subdivision-instructions/.copilot/* .copilot/ || echo "No subdivision-level instructions to merge"
          echo "copilot merge completed"

      - name: Commit if changed
        if: env.ORG != ''
        run: |
          git config user.name "copilot-bot"
          git config user.email "copilot-bot@yourcompany.com"
          git add .copilot
          git diff --quiet || git commit -m "sync: subdivision Copilot instructions"
          git push
